src/App.js
src/domain/controls.js
src/domain/dataset.js
src/domain/dataset.test.js
src/epics/root-epic.js
src/epics/search-dataset-epic.js
src/features/search/SearchControls.js
src/features/search/SearchControls.module.css
src/features/visualization/Visualization.js
src/features/visualization/Visualization.module.css
src/features/visualization/d3-viz.js
src/features/visualization/d3-viz/append-circles.js
src/features/visualization/d3-viz/to-hierarchy.js

#46 - adds search functionality

Add search

---

src/epics/load-dataset-epic.js

While checking issue #60, found an inconsistency between intent (checking for multiple lines in CSV file) and actual code implementation (checking number of headers). This has been fixed.

Fixed one of the file checks in CSV import processing.

---

.eslintrc
package-lock.json
package.json
src/domain/dataset.js
src/epics/epic.test.js
src/epics/fetch-dataset-epic.js
src/epics/load-dataset-epic.js
src/epics/search-dataset-epic.js
src/epics/upload-dataset-epic.js
src/features/search/SearchControls.js
src/index.js

Dependency resolution

---

Dockerfile.gh

Fixes #84 by adding git seperately

fix: git not found error

---

.travis.yml

- closes #86 - added docker build instructions to travis config.

chore: 86 - Add Docker build to Travis

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md

templates for:
-bug reporting
-feature request

chore: Add issue templates

---

package-lock.json
src/features/visualization/Visualization.module.css
src/features/visualization/d3-viz/append-circles.js
src/features/visualization/d3-viz/setup-legend.js

- get rid of automatic application of styles based on hardcoded value of "Unknown"
- fixes #91
removes automatic application of style the colors unknown nodes red
No

feat: Remove default red

---

.mocha
package-lock.json
src/epics/epic.test.js
src/epics/index-dataset-epic.js
src/epics/search-dataset-epic.js
src/test/test-dom.js

…efully
added a block to catch this error and made sure results were set to [] rather than null
N/A

Search improvements

---

.mocha
package-lock.json
package.json
src/domain/root-reducer.js
src/epics/epic.test.js
src/epics/index-dataset-epic.js
src/epics/load-dataset-epic.js
src/features/dataset-controls/DatasetDownload.test.js
src/features/dataset-controls/DatasetRefresh.test.js
src/features/dataset-controls/DatasetSelector.test.js
src/features/search/SearchControls.js
src/features/search/SearchControls.test.js
src/test/ignore-styles.js
src/test/test-dom.js

added several UI unit tests to use as a model
N/A

Ui testing

---

src/epics/epic.test.js
src/epics/search-dataset-epic.js
src/epics/upload-dataset-epic.js

chore(tesing): improve test coverage in epics

---

.snyk
package-lock.json
package.json
src/features/dataset-controls/DatasetRefresh.js

updates dependencies to remediate vulnerabilities
N/A

fix: dependency updates to remediate vulns flagged by Snyk

---

src/features/dataset-controls/DatasetControls.js

corrects mechanism of supplying url to autorefresh mechanism
No

126 map undefined

---

src/App.js
src/features/dataset-controls/DatasetControls.js
src/features/dataset-controls/DatasetUpload.js

pass owner uuid to sub control to use in id in order to prevent id collisions when using html for
No

fix: Closes #152

---

Dockerfile.gh
package.json

automatically inserts Google Analytics code to index.html during deployment
No

chore: adds Google Analytics code to index.html during deployment

---

src/App.js

switch from conditional rendering to style display: none to preserve state of the search control.  
No

Fixes #160 

---

package-lock.json
package.json
src/App.js
src/domain/dataset.js
src/domain/dataset.test.js
src/domain/filter.js
src/domain/filter.test.js
src/domain/root-reducer.js
src/epics/epic.test.js
src/epics/filter-dataset-epic.js
src/epics/root-epic.js
src/epics/search-dataset-epic.js

Sets up the backend infrastructure necessary to perform filtering on a dataset
No

112 filter ui

---

.mocha
package-lock.json
package.json

- updates to babel 7.x.x
- updated dev and test config to move from babel- notation to @babel/ notation
Updates dev dependencies to use latest version of babel
No

fix: Closes #166

---

src/features/visualization/d3-viz/pack-with-label.js
src/features/visualization/d3-viz/setup-legend.js

removed unnecessary debug code
None

chore: remove debug code

---

src/App.js
src/App.module.css

fix: Fixes #175 - added text stating that a dataset needs loaded

---

README.md

What does this pr accomplish and why should it be integrated?

Expand instructions for building without docker

---

src/features/header/Header.js

Fixes: 183 made the logo a link
No

chore: added link to CyberReboot logo

---

package-lock.json
package.json

bump back to dev

---

src/features/misc-controls/FieldSelect.js
src/features/misc-controls/MiscControls.js
src/features/misc-controls/MiscControls.module.css

corrects styling of the color by `<select>`
None

fix: Closes #191 - corrected styling on Color By select element

---

src/App.js
src/features/visualization/d3-viz.js

(except dark theme and zoom)
- closes #101
adds a button to reset display options 
Zoom reset will be added to this button as part of #102

feat: adds a button to reset display options 

---

src/features/header/Header.js

updates the copyright info in the header to match the license file
No

updated copyright info in header

---

package-lock.json
package.json

closes #209
closes #210
closes #211
N/A

fix(dependencies): removed react-app-rewired

---

package-lock.json
package.json
src/domain/dataset.js
src/epics/index-dataset-epic.js
src/features/visualization/d3-viz/setup-legend.js

fixes issues with empty field paths
N/A

fix: Closes #206 - corrects issue with field paths

---

Dockerfile

uses the `--no-cache` flag rather than the `--update` flag and removes the cleanup of `/var/cache/apk/`
No

updates dockerfile for more correct usage of apk and healthcheck

---

src/epics/index-dataset-epic.js
src/features/dataset-controls/DatasetControls.js

fix: remove hard coding of port and debug code

---

Dockerfile.experimental.gh
package-lock.json
package.json

-add dockerfile for experimental location
-fixes #253
adds a dockerfile to deploy to my github.io location
No

chore: bump back to dev

---

package-lock.json
package.json

updates react-scripts to version 2.1.5
No

fix: update react-scripts to 2.1.5. fixes #255

---

src/App.module.css
src/features/visualization/Visualization.module.css

closes #348
corrects the "changed" icon in the key
N/A

fix: css fix for key

---

package-lock.json
package.json

closes #352
removes unused dependency d3-svg-annotation
- [x ] Lint and unit tests pass locally with my changes
N/A

fix(deps): remove unused dependency d3-svg-annotation

---

LICENSE
src/features/header/Header.js

Update copyright info

---

.travis.yml

switch from `npm install` to `npm ci`
Closes #401

switch from install to ci

---

Dockerfile
Dockerfile.experimental.gh
Dockerfile.gh

Dockerfiles use the same build setup as Travis.
Closes #405
No

update Dockerfiles to match travis build

---

package-lock.json
package.json
src/features/header/Header.js
src/features/header/Header.module.css

adds links for:
- github
- twitter
- medium
closes #421 
No

fix: add social media links

---

src/features/tooltip/Tooltip.js
src/features/tooltip/Tooltip.module.css

Closes #453
add dark theme for tooltip
No

add dark theme for tooltip

---

package-lock.json
package.json

downgrade gh-pages to 2.0.0
Closes #456
No

downgrade gh-pages to 2.0.0

---

src/features/tooltip/Tooltip.js

terate over field list in configuration and get fields values
Fixes #484
No

remove hardcoding of tooltip fields

---

src/features/tooltip/Tooltip.js
src/features/visualization/d3-viz.js

remove debug code

---

src/features/tooltip/Tooltip.js
src/features/tooltip/Tooltip.module.css

- makes notes panel collapsible and scrollable
- fixes note toggle's dark mode appearance
closes #499
No

fix: makes notes panel collapsible and scrollable

---

src/features/visualization/Visualization.module.css

Makes the grouping labels black even in dark mode for better contrast
fixes #540 

fix: change color of grouping label text in dark mode

---

.eslintrc
config-overrides.js
package-lock.json
package.json

fixes dependency issue causing linting to fail. 

linting fixes

---

.mocha
.mocharc.json
package.json

- remove deprecated `.mocha` file
- move options into `.mocharc.json`
- closes #683
No

Update mocha for deprecation

---

.github/workflows/nodejs.yml
.github/workflows/workflows/docker.yml
.github/workflows/workflows/nodejs.yml
package-lock.json
package.json

removes version 8.x of node.js from testing
No

remove node 8.x testing

---

CHANGELOG.md
package-lock.json
package.json

release v0.3.23

---

package-lock.json
package.json
src/features/visualization/d3-viz/setup-zoom.js

Updates D3 to v6.2.0 and deals with breaking changes introduced in D3 version 6.
N

update dependency d3 to v6.2.0

---

CHANGELOG.md
package-lock.json
package.json

release 0.3.25

---

CHANGELOG.md
package-lock.json
package.json

release v0.3.26

---

CHANGELOG.md
package-lock.json
package.json

Release 0.3.27
